// Gabarito Oficial — Capítulo: 05-operadores-e-expressoes — Exercício 3

algoritmo "Operacoes Basicas"
var
   a, b: inteiro

inicio
   escreva("Digite o primeiro numero: ")
   leia(a)
   escreva("Digite o segundo numero: ")
   leia(b)

   escreval("Soma: ", a + b)
   escreval("Subtracao: ", a - b)
   escreval("Produto: ", a * b)
   escreval("Divisao real: ", a / b)
   escreval("Resto da divisao: ", a mod b)
fimalgoritmo
